# docker-compose.yml (project root)

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       pg-energy-monitor
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"    # host:container

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    env_file:
      - backend/.env
    environment:
      POSTGRES_SERVER:     db
      POSTGRES_DB:         pg-energy-monitor
      ENABLE_SIMULATION:   "false"
    volumes:
      - ./backend:/app    # live code-reload
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://backend:8000/api/v1"
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./frontend:/app          # live code
      - frontend_node_modules:/app/node_modules  # keep installed deps

volumes:
  db_data:
  frontend_node_modules: